server:
    error:
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/Animes?createDatabaseIfNotExist=true
        username: root
        password: 123456aA#
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true